import { buildSearchKeywords, vehicleSlug } from "@/utils/slug";
import type { Vehicle, VehicleFeature } from "@/types";

function vehicle(input: Omit<Vehicle, "slug" | "searchKeywords" | "primaryImage"> & { primaryImage?: string }): Vehicle {
  const images = input.images;
  const primaryImage = input.primaryImage || images[0]?.url || "/cover.jpg";
  return {
    ...input,
    primaryImage,
    slug: vehicleSlug(input),
    searchKeywords: buildSearchKeywords(input),
  };
}

const features = (list: VehicleFeature[]): VehicleFeature[] => list;

export const DEMO_VEHICLES: Vehicle[] = [
  vehicle({
    id: "v_premio_2022",
    stockId: "HT-001",
    make: "Toyota",
    model: "Premio",
    variant: "G Superior",
    year: 2022,
    price: 12750000,
    currency: "LKR",
    mileage: 18500,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    engine: "1.8L",
    color: "Pearl White",
    condition: "Excellent",
    registrationStatus: "Registered",
    description:
      "A well-kept Toyota Premio with a clean cabin, smooth automatic gearbox, and complete service history available on request. Suitable for family and executive use.",
    features: features([
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Reverse Camera",
      "Leather Seats",
      "Alloy Wheels",
      "ABS",
      "Airbags",
      "Push Start",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1600&q=80",
        path: "demo/premio-1.jpg",
        alt: "Toyota Premio front three-quarter view",
        sortOrder: 0,
      },
      {
        url: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1600&q=80",
        path: "demo/premio-2.jpg",
        alt: "White sedan side profile",
        sortOrder: 1,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: true,
    createdAt: "2026-08-12T08:00:00.000Z",
    updatedAt: "2026-08-12T08:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_axio_2021",
    stockId: "HT-002",
    make: "Toyota",
    model: "Axio",
    variant: "Hybrid",
    year: 2021,
    price: 8450000,
    currency: "LKR",
    mileage: 31200,
    fuelType: "Hybrid",
    transmission: "CVT",
    bodyType: "Sedan",
    engine: "1.5L Hybrid",
    color: "Silver",
    condition: "Very Good",
    registrationStatus: "Registered",
    description:
      "Fuel-efficient Toyota Axio Hybrid with a practical sedan body and a tidy interior. A strong everyday choice for city and highway driving.",
    features: features([
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Bluetooth",
      "ABS",
      "Airbags",
      "Alloy Wheels",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1549927681-0b673b8243ab?auto=format&fit=crop&w=1600&q=80",
        path: "demo/axio-1.jpg",
        alt: "Silver sedan in daylight",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: true,
    createdAt: "2026-08-18T09:30:00.000Z",
    updatedAt: "2026-08-18T09:30:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_vezel_2023",
    stockId: "HT-003",
    make: "Honda",
    model: "Vezel",
    variant: "RS Honda Sensing",
    year: 2023,
    price: 13900000,
    currency: "LKR",
    mileage: 9800,
    fuelType: "Hybrid",
    transmission: "CVT",
    bodyType: "Crossover",
    engine: "1.5L Hybrid",
    color: "Modern Steel",
    condition: "Excellent",
    registrationStatus: "Registered",
    description:
      "Low-mileage Honda Vezel with a versatile crossover stance and a well-equipped cabin. Ideal if you want extra height and cargo space without moving into a large SUV.",
    features: features([
      "Air Conditioning",
      "Climate Control",
      "Reverse Camera",
      "Apple CarPlay",
      "Android Auto",
      "Keyless Entry",
      "Push Start",
      "Cruise Control",
      "ABS",
      "Airbags",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1600&q=80",
        path: "demo/vezel-1.jpg",
        alt: "Honda crossover on the road",
        sortOrder: 0,
      },
      {
        url: "https://images.unsplash.com/photo-1511919884226-fd3cad34687a?auto=format&fit=crop&w=1600&q=80",
        path: "demo/vezel-2.jpg",
        alt: "Crossover rear three-quarter",
        sortOrder: 1,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: true,
    createdAt: "2026-08-22T11:00:00.000Z",
    updatedAt: "2026-08-22T11:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_wagonr_2020",
    stockId: "HT-004",
    make: "Suzuki",
    model: "Wagon R",
    variant: "Stingray",
    year: 2020,
    price: 4950000,
    currency: "LKR",
    mileage: 42100,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Hatchback",
    engine: "660cc",
    color: "Blue",
    condition: "Good",
    registrationStatus: "Registered",
    description:
      "A compact, easy-to-park Suzuki Wagon R with tall seating and low running costs. Useful as a first car or a dependable city runabout.",
    features: features([
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "ABS",
      "Airbags",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1600&q=80",
        path: "demo/wagonr-1.jpg",
        alt: "Compact hatchback",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: false,
    createdAt: "2026-07-30T07:15:00.000Z",
    updatedAt: "2026-07-30T07:15:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_xtrail_2024",
    stockId: "HT-005",
    make: "Nissan",
    model: "X-Trail",
    variant: "ST-L",
    year: 2024,
    price: 18950000,
    currency: "LKR",
    mileage: 1200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.5L",
    color: "Black",
    condition: "Like New",
    registrationStatus: "Unregistered",
    description:
      "Near-new Nissan X-Trail with very low mileage. Spacious family SUV with a commanding driving position and a quiet cabin.",
    features: features([
      "Climate Control",
      "Leather Seats",
      "Sunroof",
      "Reverse Camera",
      "Parking Sensors",
      "Apple CarPlay",
      "Android Auto",
      "Cruise Control",
      "Keyless Entry",
      "Push Start",
      "Alloy Wheels",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1600&q=80",
        path: "demo/xtrail-1.jpg",
        alt: "Black SUV front view",
        sortOrder: 0,
      },
      {
        url: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1600&q=80",
        path: "demo/xtrail-2.jpg",
        alt: "SUV on a scenic road",
        sortOrder: 1,
      },
    ],
    location: "Showroom",
    vehicleType: "new",
    status: "available",
    featured: true,
    createdAt: "2026-09-01T10:00:00.000Z",
    updatedAt: "2026-09-01T10:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_civic_2019",
    stockId: "HT-006",
    make: "Honda",
    model: "Civic",
    variant: "RS",
    year: 2019,
    price: 11200000,
    currency: "LKR",
    mileage: 47800,
    fuelType: "Petrol",
    transmission: "CVT",
    bodyType: "Sedan",
    engine: "1.5L Turbo",
    color: "Rallye Red",
    condition: "Very Good",
    registrationStatus: "Registered",
    description:
      "A sharper Honda Civic RS with turbo performance and a driver-focused cabin. Maintained for a confident daily drive.",
    features: features([
      "Climate Control",
      "Apple CarPlay",
      "Android Auto",
      "Sunroof",
      "Leather Seats",
      "Cruise Control",
      "Alloy Wheels",
      "Fog Lights",
      "ABS",
      "Airbags",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&w=1600&q=80",
        path: "demo/civic-1.jpg",
        alt: "Red Honda Civic",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "reserved",
    featured: false,
    createdAt: "2026-08-05T06:40:00.000Z",
    updatedAt: "2026-09-02T12:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_landcruiser_2018",
    stockId: "HT-007",
    make: "Toyota",
    model: "Land Cruiser Prado",
    variant: "TX",
    year: 2018,
    price: 32500000,
    currency: "LKR",
    mileage: 62400,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.8L Diesel",
    color: "White",
    condition: "Very Good",
    registrationStatus: "Registered",
    description:
      "A capable Toyota Land Cruiser Prado with the space and presence expected of a full-size SUV. Presented with a clear description and available for inspection.",
    features: features([
      "Climate Control",
      "Leather Seats",
      "Sunroof",
      "Reverse Camera",
      "Parking Sensors",
      "Cruise Control",
      "Keyless Entry",
      "Alloy Wheels",
      "ABS",
      "Airbags",
      "Navigation",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80",
        path: "demo/prado-1.jpg",
        alt: "White Toyota SUV",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: true,
    createdAt: "2026-07-12T05:00:00.000Z",
    updatedAt: "2026-07-12T05:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_alto_2022",
    stockId: "HT-008",
    make: "Suzuki",
    model: "Alto",
    variant: "LXi",
    year: 2022,
    price: 3650000,
    currency: "LKR",
    mileage: 15600,
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    engine: "800cc",
    color: "White",
    condition: "Excellent",
    registrationStatus: "Registered",
    description:
      "Simple, economical Suzuki Alto with low mileage. A practical choice if you want a straightforward car with modest running costs.",
    features: features([
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "ABS",
      "Airbags",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?auto=format&fit=crop&w=1600&q=80",
        path: "demo/alto-1.jpg",
        alt: "Small white hatchback",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: false,
    createdAt: "2026-09-04T08:20:00.000Z",
    updatedAt: "2026-09-04T08:20:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_camry_2024",
    stockId: "HT-009",
    make: "Toyota",
    model: "Camry",
    variant: "Hybrid",
    year: 2024,
    price: 21400000,
    currency: "LKR",
    mileage: 450,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    engine: "2.5L Hybrid",
    color: "Attitude Black",
    condition: "New",
    registrationStatus: "Unregistered",
    description:
      "New Toyota Camry Hybrid with a refined ride and a quiet cabin. A premium sedan for comfortable long-distance and city driving.",
    features: features([
      "Climate Control",
      "Leather Seats",
      "Sunroof",
      "Apple CarPlay",
      "Android Auto",
      "Reverse Camera",
      "Parking Sensors",
      "Cruise Control",
      "Keyless Entry",
      "Push Start",
      "Alloy Wheels",
      "ABS",
      "Airbags",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1600&q=80",
        path: "demo/camry-1.jpg",
        alt: "Black luxury sedan",
        sortOrder: 0,
      },
      {
        url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=80",
        path: "demo/camry-2.jpg",
        alt: "Sedan interior and dash",
        sortOrder: 1,
      },
    ],
    location: "Showroom",
    vehicleType: "new",
    status: "available",
    featured: true,
    createdAt: "2026-09-06T14:00:00.000Z",
    updatedAt: "2026-09-06T14:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_hilux_2021",
    stockId: "HT-010",
    make: "Toyota",
    model: "Hilux",
    variant: "Double Cab",
    year: 2021,
    price: 16800000,
    currency: "LKR",
    mileage: 38900,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Pickup",
    engine: "2.8L Diesel",
    color: "Grey",
    condition: "Very Good",
    registrationStatus: "Registered",
    description:
      "Work-ready Toyota Hilux double cab with an automatic gearbox. Useful as a dual-purpose vehicle for business and family use.",
    features: features([
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
      "Reverse Camera",
      "Bluetooth",
      "ABS",
      "Airbags",
      "Alloy Wheels",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=1600&q=80",
        path: "demo/hilux-1.jpg",
        alt: "Pickup truck on a road",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "available",
    featured: false,
    createdAt: "2026-08-28T04:10:00.000Z",
    updatedAt: "2026-08-28T04:10:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_leaf_2019",
    stockId: "HT-011",
    make: "Nissan",
    model: "Leaf",
    variant: "G",
    year: 2019,
    price: 6200000,
    currency: "LKR",
    mileage: 27400,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Hatchback",
    engine: "Electric",
    color: "White",
    condition: "Good",
    registrationStatus: "Registered",
    description:
      "Nissan Leaf for quiet, zero-petrol daily driving. Battery condition and charging details can be discussed during inspection.",
    features: features([
      "Climate Control",
      "Push Start",
      "Bluetooth",
      "Reverse Camera",
      "ABS",
      "Airbags",
      "Alloy Wheels",
    ]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1600&q=80",
        path: "demo/leaf-1.jpg",
        alt: "Electric hatchback charging",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "sold",
    featured: false,
    createdAt: "2026-06-15T09:00:00.000Z",
    updatedAt: "2026-08-20T09:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
  vehicle({
    id: "v_draft_mazda",
    stockId: "HT-012",
    make: "Mazda",
    model: "CX-5",
    variant: "Touring",
    year: 2020,
    price: 13250000,
    currency: "LKR",
    mileage: 41000,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    engine: "2.0L",
    color: "Soul Red",
    condition: "Very Good",
    registrationStatus: "Registered",
    description: "Draft listing — not visible on the public website until published.",
    features: features(["Climate Control", "Leather Seats", "Apple CarPlay", "ABS", "Airbags"]),
    images: [
      {
        url: "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1600&q=80",
        path: "demo/cx5-1.jpg",
        alt: "Red Mazda SUV",
        sortOrder: 0,
      },
    ],
    location: "Showroom",
    vehicleType: "used",
    status: "draft",
    featured: false,
    createdAt: "2026-09-08T16:00:00.000Z",
    updatedAt: "2026-09-08T16:00:00.000Z",
    createdBy: "demo",
    updatedBy: "demo",
  }),
];
